[windows]
#desktop-83dairh ansible_host=192.168.56.104
#winvm ansible_host=192.168.56.104
winvm ansible_host=192.168.56.105

[windows:vars]
ansible_user=ansibleuser
ansible_password=Vishnu@2306
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=ntlm
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_operation_timeout_sec=60
ansible_winrm_read_timeout_sec=120
#newrelic_license_key=a9790368e394889b5ef87f795b982ab2FFFFNRAL

