<<<<<<< HEAD
- name: Upgrade New Relic Infrastructure Agent to 1.69.0 (Windows)
=======
- name: Upgrade New Relic Infrastructure Agent to 1.69.0 (Windows.)
>>>>>>> 64cfb9c (changed the version)
  hosts: windows
  gather_facts: no

  vars:
    nr_license_key: "{{ lookup('env', 'NEW_RELIC_LICENSE_KEY') }}"

  tasks:

    - name: Ensure New Relic config directory exists
      ansible.windows.win_file:
        path: C:\Program Files\New Relic\newrelic-infra
        state: directory

    - name: Write New Relic license key to config file
      ansible.windows.win_copy:
        dest: C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml
        content: |
          license_key: "{{ nr_license_key }}"
          log_level: info

    - name: Download New Relic Infrastructure Agent MSI
      ansible.windows.win_get_url:
        url: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.1.69.0.msi
        dest: C:\Temp\newrelic-infra.msi

    - name: Install / Upgrade New Relic Infrastructure Agent (in-place)
      ansible.windows.win_package:
        path: C:\Temp\newrelic-infra.msi
        state: present
        arguments: /qn

    - name: Restart New Relic Infrastructure Agent
      ansible.windows.win_service:
        name: newrelic-infra
        state: restarted
