---
- name: NPROD | WinRM HTTPS Test
  hosts: all
  gather_facts: no

  tasks:
    - name: WinRM ping
      ansible.windows.win_ping

    - name: Get hostname
      ansible.windows.win_command: hostname

    - debug:
        msg: "WinRM HTTPS connection successful"
